theme: jekyll-theme-slate
title: Disconnected Data Distribution
description: Bringing Internet Services to Disconnected Areas of the World
github:
    repository_url: https://github.com/SJSU-CS-systems-group/DDD
